### ISSUE TITLE
Softwrap long lines

### ISSUE THREAD

**Issue by bofeiw** [rajinwonderland/react-code-blocks#30]
Hi, it'll be good if I can soft-wrap long code in a line by passing in a parameter like softWrap={true}.

Currently I need to write custom css to implement soft-wrap. It works but nice to add in this feature.
```css
code {
  max-width: 90%;
  overflow-wrap: break-word;
}
```
